version: '3.8'

services:
  agent:
    build: .
    container_name: DMSpadeController-agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      XMPP_DOMAIN: "isc-coordinator.lan"
      XMPP_USERNAME: "alphabot23-agent"
      XMPP_PASSWORD: "top_secret"
      PYTHONUNBUFFERED: 1
    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
    volumes:
      - ./agent:/agent
