version: '3.8'

services:
  agent:
    build: .
    container_name: spadecontroller-agent
    profiles: ["agent"]
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
      - /dev/dma_heap:/dev/dma_heap
    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
      - "isc-coordinator2.lan:192.168.88.226"
#      - "isc-coordinator2.lan:192.168.31.163"
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      LIBCAMERA_LOG_LEVELS: "*:ERROR"
    ports:
      - "8000:8000"   # Camera stream
    volumes:
      - /run/udev:/run/udev:ro
      - ./agent:/agent
    env_file:
      - ./.env.remote
  test-agent:
    build: .
    container_name: spadecontroller-test
    profiles: ["test"]
    privileged: false
    devices:
      - /dev/gpiomem:/dev/gpiomemsomehwe
    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
      - "isc-coordinator2.lan:192.168.88.226"
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      LIBCAMERA_LOG_LEVELS: "*:ERROR"
    volumes:
      - ./agent:/agent
    env_file:
      - ./.env.remote
    command: python agent/TestAgent.py
