#!/bin/bash
# Implemented with assistance from AI (Copilot)
# Deployment script for SpadeController
LOGFILE=deploy.log
echo "$(date) - Deployment started" >> $LOGFILE
echo "$(date) - Deployment started"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_PATH="${SCRIPT_DIR}"

# Load .env file (local config for deployment)
ENV_FILE="${LOCAL_PATH}/.env.template"
if [ -f $ENV_FILE ]; then
    source $ENV_FILE
else
    echo "$ENV_FILE file not found" >> $LOGFILE
    echo "$ENV_FILE file not found"
    exit 1
fi

# Validate required variables
REQUIRED_VARS=(REMOTE_USER REMOTE_PATH XMPP_PASSWORD)
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        echo "Error: $var is not set in $ENV_FILE" >> $LOGFILE
        echo "Error: $var is not set in $ENV_FILE"
        exit 1
    fi
done

# Select bot to deploy on
read -rp "Select bot to deploy on (1-4): " bot_choice
if [[ ! $bot_choice =~ ^[1-4]$ ]]; then
    echo "Invalid bot id, choice ${bot_choice}. Exiting." >> $LOGFILE
    echo "Invalid bot id, choice ${bot_choice}. Exiting."
    exit 1
fi

# Select coordinator to deploy on
read -rp "Select coordinator to deploy on (1-2): " coordinator
if [[ ! $coordinator =~ ^[1-2]$ ]]; then
    echo "Invalid coordinator choice ${coordinator}. Exiting." >> $LOGFILE
    echo "Invalid coordinator choice ${coordinator}. Exiting."
    exit 1
fi

REMOTE_HOST_VAR="REMOTE_HOST_${bot_choice}"
XMPP_USERNAME_VAR="XMPP_USERNAME_${bot_choice}"
XMPP_DOMAIN_VAR="XMPP_DOMAIN_${coordinator}"

REMOTE_HOST="${!REMOTE_HOST_VAR}"
XMPP_USERNAME="${!XMPP_USERNAME_VAR}"
XMPP_DOMAIN="${!XMPP_DOMAIN_VAR}"

# Validate specific values
if [ -z "$REMOTE_HOST" ] || [ -z "$XMPP_USERNAME" ] || [ -z "$XMPP_DOMAIN" ]; then
    echo "Missing specific configuration for bot ${bot_choice} or coordinator ${coordinator}" >> $LOGFILE
    echo "Missing specific configuration for bot ${bot_choice} or coordinator ${coordinator}"
    exit 1
fi

# Set the agent name for XMPP
MOTION_AGENT="motion-${XMPP_USERNAME}@${XMPP_DOMAIN}"
CAMERA_AGENT="camera-${XMPP_USERNAME}@${XMPP_DOMAIN}"
SENSORS_AGENT="sensors-${XMPP_USERNAME}@${XMPP_DOMAIN}"

# Generate .env file for the selected bot
TEMPLATE="${LOCAL_PATH}/.env.template"
OUTPUT="${LOCAL_PATH}/.env.remote"

if [ ! -f "$TEMPLATE" ]; then
    echo "Missing .env.template in SpadeController" >> $LOGFILE
    echo "Missing .env.template in SpadeController"
    exit 1
fi

cp "$TEMPLATE" "$OUTPUT"

# Add header comment
tmpfile=$(mktemp)
{
    echo "# ---------------------------------------------------------"
    echo "# This file was generated automatically by deploy_spadecontroller.sh"
    echo "# Do NOT edit this file manually."
    echo "# If you need to change values, edit .env.template or .env"
    echo "# ---------------------------------------------------------"
    echo
    echo "# Generated for bot $bot_choice on coordinator $coordinator"
    echo
    cat "$OUTPUT"
} > "$tmpfile"

mv "$tmpfile" "$OUTPUT"


sed -i "s|{{REMOTE_HOST}}|$REMOTE_HOST|g" "$OUTPUT"
sed -i "s|{{XMPP_USERNAME}}|$XMPP_USERNAME|g" "$OUTPUT"
sed -i "s|{{XMPP_PASSWORD}}|$XMPP_PASSWORD|g" "$OUTPUT"
sed -i "s|{{XMPP_DOMAIN}}|$XMPP_DOMAIN|g" "$OUTPUT"

sed -i "s|{{MOTION_AGENT}}|$MOTION_AGENT|g" "$OUTPUT"
sed -i "s|{{CAMERA_AGENT}}|$CAMERA_AGENT|g" "$OUTPUT"
sed -i "s|{{SENSORS_AGENT}}|$SENSORS_AGENT|g" "$OUTPUT"

echo "Generated .env for bot $bot_choice on coordinator $coordinator" >> $LOGFILE
echo "Generated .env for bot $bot_choice on coordinator $coordinator"
# ---------------------------------------------------------

# Default values
SSH_PORT=${SSH_PORT:-22}
RSYNC_OPTS=${RSYNC_OPTS:--avz --delete --exclude='.env' --exclude='.env.template'}

echo "Deploying folder to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}" >> $LOGFILE
echo "Using rsync options: ${RSYNC_OPTS}" >> $LOGFILE
echo "XMPP base JID will be: ${XMPP_USERNAME}@${XMPP_DOMAIN}" >> $LOGFILE
echo "Deploying folder to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
echo "Using rsync options: ${RSYNC_OPTS}"
echo "XMPP base JID will be: ${XMPP_USERNAME}@${XMPP_DOMAIN}"

# Confirm deployment
read -rp "Proceed with deployment? (y/n) " confirm
[[ "$confirm" != "y" ]] && exit 0

# Run rsync
rsync ${RSYNC_OPTS} -e "ssh -p ${SSH_PORT}" \
    "${LOCAL_PATH}/" \
    "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/"

rm ${OUTPUT}

echo "Deployment complete." >> $LOGFILE
echo "Deployment complete."
